import * as schema from '../../src/lib/server/db/schema.ts';

/** @description The base essences. This does not include confluence essences */
export const essences: (typeof schema.essences.$inferInsert)[] = [
	{ name: 'Adept', rarity: 'common' },
	{ name: 'Ape', rarity: 'common' },
	{ name: 'Armour', rarity: 'common' },
	{ name: 'Axe', rarity: 'common' },
	{ name: 'Balance', rarity: 'uncommon' },
	{ name: 'Bat', rarity: 'common' },
	{ name: 'Bear', rarity: 'common' },
	{ name: 'Bee', rarity: 'common' },
	{ name: 'Bird', rarity: 'common' },
	{ name: 'Blight' },
	{ name: 'Blood', rarity: 'uncommon' },
	{ name: 'Bone', rarity: 'uncommon' },
	{ name: 'Bow', rarity: 'common' },
	{ name: 'Cage', rarity: 'common' },
	{ name: 'Cat', rarity: 'common' },
	{ name: 'Cattle', rarity: 'common' },
	{ name: 'Chain', rarity: 'common' },
	{ name: 'Claw', rarity: 'uncommon' },
	{ name: 'Cloth', rarity: 'common' },
	{ name: 'Cloud', rarity: 'uncommon' },
	{ name: 'Cold', rarity: 'uncommon' },
	{ name: 'Coral', rarity: 'common' },
	{ name: 'Corrupt', rarity: 'epic' },
	{ name: 'Crocodile', rarity: 'common' },
	{ name: 'Crystal', rarity: 'rare' },
	{ name: 'Dance', rarity: 'uncommon' },
	{ name: 'Dark', rarity: 'uncommon' },
	{ name: 'Death', rarity: 'uncommon' },
	{ name: 'Deep', rarity: 'rare' },
	{ name: 'Deer', rarity: 'common' },
	{ name: 'Dimension', rarity: 'legendary' },
	{ name: 'Discord', rarity: 'epic' },
	{ name: 'Dog', rarity: 'common' },
	{ name: 'Duck', rarity: 'common' },
	{ name: 'Dust', rarity: 'uncommon' },
	{ name: 'Earth', rarity: 'common' },
	{ name: 'Echo', rarity: 'rare' },
	{ name: 'Elemental', rarity: 'epic' },
	{ name: 'Eye', rarity: 'common' },
	{ name: 'Feast', rarity: 'common' },
	{ name: 'Feeble' },
	{ name: 'Fire', rarity: 'common' },
	{ name: 'Fish', rarity: 'common' },
	{ name: 'Flea', rarity: 'common' },
	{ name: 'Flesh', rarity: 'uncommon' },
	{ name: 'Foot', rarity: 'common' },
	{ name: 'Fork', rarity: 'common' },
	{ name: 'Fox', rarity: 'common' },
	{ name: 'Frog', rarity: 'common' },
	{ name: 'Fungus', rarity: 'common' },
	{ name: 'Gathering', rarity: 'rare' },
	{ name: 'Glass', rarity: 'uncommon' },
	{ name: 'Goat', rarity: 'common' },
	{ name: 'Grazen', rarity: 'common' },
	{ name: 'Growth', rarity: 'uncommon' },
	{ name: 'Gun', rarity: 'common' },
	{ name: 'Hair', rarity: 'common' },
	{ name: 'Hammer', rarity: 'common' },
	{ name: 'Hand', rarity: 'common' },
	{ name: 'Harmonic', rarity: 'epic' },
	{ name: 'Heidel', rarity: 'common' },
	{ name: 'Hook', rarity: 'common' },
	{ name: 'Horse', rarity: 'common' },
	{ name: 'Hunger', rarity: 'rare' },
	{ name: 'Hunt', rarity: 'common' },
	{ name: 'Ice', rarity: 'uncommon' },
	{ name: 'Iron', rarity: 'common' },
	{ name: 'Knife', rarity: 'common' },
	{ name: 'Knowledge', rarity: 'uncommon' },
	{ name: 'Life', rarity: 'uncommon' },
	{ name: 'Light', rarity: 'uncommon' },
	{ name: 'Lightning', rarity: 'uncommon' },
	{ name: 'Lizard', rarity: 'common' },
	{ name: 'Locust', rarity: 'common' },
	{ name: 'Lurker' },
	{ name: 'Magic', rarity: 'common' },
	{ name: 'Malign', rarity: 'epic' },
	{ name: 'Manatee', rarity: 'common' },
	{ name: 'Might', rarity: 'common' },
	{ name: 'Mirror', rarity: 'uncommon' },
	{ name: 'Monkey', rarity: 'common' },
	{ name: 'Moon', rarity: 'rare' },
	{ name: 'Mouse', rarity: 'common' },
	{ name: 'Myriad', rarity: 'legendary' },
	{ name: 'Needle', rarity: 'common' },
	{ name: 'Net', rarity: 'common' },
	{ name: 'Octopus', rarity: 'common' },
	{ name: 'Omen', rarity: 'epic' },
	{ name: 'Pangolin', rarity: 'common' },
	{ name: 'Paper', rarity: 'common' },
	{ name: 'Plant', rarity: 'common' },
	{ name: 'Potent', rarity: 'epic' },
	{ name: 'Pure', rarity: 'uncommon' },
	{ name: 'Rabbit', rarity: 'common' },
	{ name: 'Rake', rarity: 'common' },
	{ name: 'Rat', rarity: 'common' },
	{ name: 'Renewal', rarity: 'epic' },
	{ name: 'Resolute', rarity: 'rare' },
	{ name: 'Rune', rarity: 'epic' },
	{ name: 'Sand', rarity: 'uncommon' },
	{ name: 'Sceptre', rarity: 'common' },
	{ name: 'Serene', rarity: 'rare' },
	{ name: 'Shark', rarity: 'common' },
	{ name: 'Shield', rarity: 'common' },
	{ name: 'Shimmer', rarity: 'epic' },
	{ name: 'Ship', rarity: 'common' },
	{ name: 'Shovel', rarity: 'common' },
	{ name: 'Sickle', rarity: 'common' },
	{ name: 'Sin', rarity: 'legendary' },
	{ name: 'Skunk', rarity: 'common' },
	{ name: 'Sloth', rarity: 'common' },
	{ name: 'Smoke', rarity: 'uncommon' },
	{ name: 'Snake', rarity: 'common' },
	{ name: 'Song', rarity: 'uncommon' },
	{ name: 'Spear', rarity: 'common' },
	{ name: 'Spider', rarity: 'common' },
	{ name: 'Spike', rarity: 'common' },
	{ name: 'Staff', rarity: 'common' },
	{ name: 'Star', rarity: 'rare' },
	{ name: 'Sun', rarity: 'rare' },
	{ name: 'Swift', rarity: 'common' },
	{ name: 'Sword', rarity: 'common' },
	{ name: 'Technology', rarity: 'common' },
	{ name: 'Tentacle', rarity: 'epic' },
	{ name: 'Thread', rarity: 'common' },
	{ name: 'Trap', rarity: 'common' },
	{ name: 'Tree', rarity: 'common' },
	{ name: 'Trowel', rarity: 'common' },
	{ name: 'Turtle', rarity: 'common' },
	{ name: 'Vast', rarity: 'legendary' },
	{ name: 'Vehicle', rarity: 'common' },
	{ name: 'Venom', rarity: 'uncommon' },
	{ name: 'Visage', rarity: 'legendary' },
	{ name: 'Void', rarity: 'legendary' },
	{ name: 'Wall' },
	{ name: 'Wasp', rarity: 'common' },
	{ name: 'Water', rarity: 'common' },
	{ name: 'Whale', rarity: 'common' },
	{ name: 'Wheel', rarity: 'common' },
	{ name: 'Whip', rarity: 'common' },
	{ name: 'Wind', rarity: 'common' },
	{ name: 'Wing', rarity: 'epic' },
	{ name: 'Wolf', rarity: 'common' },
	{ name: 'Wood' },
	{ name: 'Zeal', rarity: 'rare' }
];

/** @description List of confluence essences */
export const confluenceEssence = [
	{ name: 'Animate', isConfluence: 1 },
	{ name: 'Anzu', isConfluence: 1 },
	{ name: 'Arsenal', isConfluence: 1 },
	{ name: 'Avatar', isConfluence: 1 },
	{ name: 'Battlefield', isConfluence: 1 },
	{ name: 'Behemoth', isConfluence: 1 },
	{ name: 'Boundary', isConfluence: 1 },
	{ name: 'Bounty', isConfluence: 1 },
	{ name: 'Cataclysm', isConfluence: 1 },
	{ name: 'Chaotic', isConfluence: 1 },
	{ name: 'Charlatan', isConfluence: 1 },
	{ name: 'Chimera', isConfluence: 1 },
	{ name: 'Cyborg', isConfluence: 1 },
	{ name: 'Cycle', isConfluence: 1 },
	{ name: 'Dawn', isConfluence: 1 },
	{ name: 'Desolate', isConfluence: 1 },
	{ name: 'Discordant', isConfluence: 1 },
	{ name: 'Doom', isConfluence: 1 },
	{ name: 'Doppelganger', isConfluence: 1 },
	{ name: 'Dragon', isConfluence: 1 },
	{ name: 'Eclipse', isConfluence: 1 },
	{ name: 'Edifice', isConfluence: 1 },
	{ name: 'Effigy', isConfluence: 1 },
	{ name: 'Empower', isConfluence: 1 },
	{ name: 'Fertile', isConfluence: 1 },
	{ name: 'Fey', isConfluence: 1 },
	{ name: 'Firebird', isConfluence: 1 },
	{ name: 'Fortress', isConfluence: 1 },
	{ name: 'Garuda', isConfluence: 1 },
	{ name: 'Gate', isConfluence: 1 },
	{ name: 'Glimeron', isConfluence: 1 },
	{ name: 'Gorgon', isConfluence: 1 },
	{ name: 'Griffin', isConfluence: 1 },
	{ name: 'Guardian', isConfluence: 1 },
	{ name: 'Harpy', isConfluence: 1 },
	{ name: 'Harvest', isConfluence: 1 },
	{ name: 'Hydra', isConfluence: 1 },
	{ name: 'Immortal', isConfluence: 1 },
	{ name: 'Juggernaut', isConfluence: 1 },
	{ name: 'Karmic', isConfluence: 1 },
	{ name: 'Kraken', isConfluence: 1 },
	{ name: 'Leviathan', isConfluence: 1 },
	{ name: 'Lotus', isConfluence: 1 },
	{ name: 'Magitech', isConfluence: 1 },
	{ name: 'Manticore', isConfluence: 1 },
	{ name: 'Master', isConfluence: 1 },
	{ name: 'Ministration', isConfluence: 1 },
	{ name: 'Minotaur', isConfluence: 1 },
	{ name: 'Mirage', isConfluence: 1 },
	{ name: 'Monolith', isConfluence: 1 },
	{ name: 'Mystic', isConfluence: 1 },
	{ name: 'Nebula', isConfluence: 1 },
	{ name: 'Nemesis', isConfluence: 1 },
	{ name: 'Oasis', isConfluence: 1 },
	{ name: 'Ocean', isConfluence: 1 },
	{ name: 'Onslaught', isConfluence: 1 },
	{ name: 'Phantasmagoria', isConfluence: 1 },
	{ name: 'Phoenix', isConfluence: 1 },
	{ name: 'Predatory', isConfluence: 1 },
	{ name: 'Prison', isConfluence: 1 },
	{ name: 'Prosperity', isConfluence: 1 },
	{ name: 'Refracting', isConfluence: 1 },
	{ name: 'Resonating', isConfluence: 1 },
	{ name: 'Roc', isConfluence: 1 },
	{ name: 'Sacrifice', isConfluence: 1 },
	{ name: 'Scribe', isConfluence: 1 },
	{ name: 'Serpent', isConfluence: 1 },
	{ name: 'Simulacrum', isConfluence: 1 },
	{ name: 'Skirmish', isConfluence: 1 },
	{ name: 'Sky', isConfluence: 1 },
	{ name: 'Soaring', isConfluence: 1 },
	{ name: 'Sovereign', isConfluence: 1 },
	{ name: 'Stellar', isConfluence: 1 },
	{ name: 'Storm', isConfluence: 1 },
	{ name: 'Succubus', isConfluence: 1 },
	{ name: 'Swarm', isConfluence: 1 },
	{ name: 'Talisman', isConfluence: 1 },
	{ name: 'Thunderbird', isConfluence: 1 },
	{ name: 'Time', isConfluence: 1 },
	{ name: 'Tranquil', isConfluence: 1 },
	{ name: 'Transfiguration', isConfluence: 1 },
	{ name: 'Transgression', isConfluence: 1 },
	{ name: 'Troll', isConfluence: 1 },
	{ name: 'Twilight', isConfluence: 1 },
	{ name: 'Undeath', isConfluence: 1 },
	{ name: 'Unity', isConfluence: 1 },
	{ name: 'Verdant', isConfluence: 1 },
	{ name: 'Vessel', isConfluence: 1 },
	{ name: 'Vision', isConfluence: 1 },
	{ name: 'Volcano', isConfluence: 1 },
	{ name: 'Vortex', isConfluence: 1 },
	{ name: 'Weave', isConfluence: 1 },
	{ name: 'Wendigo', isConfluence: 1 },
	{ name: 'Wrath', isConfluence: 1 },
	{ name: 'Ziz', isConfluence: 1 }
];

/** @description Confluence mappings between their various essences */
export const confluenceMap = [
	{ essence1: 'Gun', essence2: 'Hand', essence3: 'Vehicle', confluence: 'Action' },
	{ essence1: 'Adept', essence2: 'Venom', essence3: 'Water', confluence: 'Alchemy' },
	{ essence1: 'Iron', essence2: 'Thread', essence3: 'Trap', confluence: 'Ambush' },
	{ essence1: 'Rune', essence2: 'Spider', essence3: 'Trap', confluence: 'Ambush' },
	{ essence1: 'Earth', essence2: 'Spike', essence3: 'Trap', confluence: 'Ambush' },
	{ essence1: 'Fire', essence2: 'Spider', essence3: 'Trap', confluence: 'Ambush' },
	{ essence1: 'Dance', essence2: 'Knowledge', essence3: 'Mirror', confluence: 'Animate' },
	{ essence1: 'Fungus', essence2: 'Growth', essence3: 'Zeal', confluence: 'Animate' },
	{ essence1: 'Dance', essence2: 'Dust', essence3: 'Echo', confluence: 'Animate' },
	{ essence1: 'Bone', essence2: 'Death', essence3: 'Magic', confluence: 'Animate' },
	{ essence1: 'Cloth', essence2: 'Dance', essence3: 'Magic', confluence: 'Animate' },
	{ essence1: 'Bird', essence2: 'Cat', essence3: 'Vast', confluence: 'Anzu' },
	{ essence1: 'Myriad', essence2: 'Shield', essence3: 'Sword', confluence: 'Arsenal' },
	{ essence1: 'Corrupt', essence2: 'Dimension', essence3: 'Magic', confluence: 'Avatar' },
	{ essence1: 'Dark', essence2: 'Tentacle', essence3: 'Void', confluence: 'Avatar' },
	{ essence1: 'Hammer', essence2: 'Lightning', essence3: 'Might', confluence: 'Avatar' },
	{ essence1: 'Blood', essence2: 'Life', essence3: 'Sun', confluence: 'Avatar' },
	{ essence1: 'Dimension', essence2: 'Might', essence3: 'Renewal', confluence: 'Avatar' },
	{ essence1: 'Lightning', essence2: 'Might', essence3: 'Sword', confluence: 'Avatar' },
	{ essence1: 'Rune', essence2: 'Spear', essence3: 'Tree', confluence: 'Avatar' },
	{ essence1: 'Potent', essence2: 'Vast', essence3: 'Water', confluence: 'Avatar' },
	{ essence1: 'Corrupt', essence2: 'Magic', essence3: 'Void', confluence: 'Avatar' },
	{ essence1: 'Corrupt', essence2: 'Dimension', essence3: 'Potent', confluence: 'Avatar' },
	{ essence1: 'Dimension', essence2: 'Tentacle', essence3: 'Void', confluence: 'Avatar' },
	{ essence1: 'Elemental', essence2: 'Harmonic', essence3: 'Potent', confluence: 'Avatar' },
	{ essence1: 'Dimension', essence2: 'Light', essence3: 'Wing', confluence: 'Avatar' },
	{ essence1: 'Eye', essence2: 'Fire', essence3: 'Magic', confluence: 'Avatar' },
	{ essence1: 'Elemental', essence2: 'Might', essence3: 'Resolute', confluence: 'Avatar' },
	{ essence1: 'Corrupt', essence2: 'Dimension', essence3: 'Might', confluence: 'Avatar' },
	{ essence1: 'Magic', essence2: 'Might', essence3: 'Potent', confluence: 'Avatar' },
	{ essence1: 'Blood', essence2: 'Bone', essence3: 'Flesh', confluence: 'Avatar' },
	{ essence1: 'Iron', essence2: 'Spike', essence3: 'Vast', confluence: 'Battlefield' },
	{ essence1: 'Cattle', essence2: 'Earth', essence3: 'Vast', confluence: 'Behemoth' },
	{ essence1: 'Balance', essence2: 'Earth', essence3: 'Shield', confluence: 'Boundary' },
	{ essence1: 'Dance', essence2: 'Feast', essence3: 'Knife', confluence: 'Bounty' },
	{ essence1: 'Hunger', essence2: 'Vast', essence3: 'Void', confluence: 'Cataclysm' },
	{ essence1: 'Dimension', essence2: 'Myriad', essence3: 'Sin', confluence: 'Cataclysm' },
	{ essence1: 'Fire', essence2: 'Potent', essence3: 'Water', confluence: 'Cataclysm' },
	{ essence1: 'Death', essence2: 'Myriad', essence3: 'Void', confluence: 'Cataclysm' },
	{ essence1: 'Balance', essence2: 'Magic', essence3: 'Potent', confluence: 'Chaotic' },
	{ essence1: 'Adept', essence2: 'Magic', essence3: 'Trap', confluence: 'Charlatan' },
	{ essence1: 'Cat', essence2: 'Tentacle', essence3: 'Void', confluence: 'Chimera' },
	{ essence1: 'Snake', essence2: 'Spider', essence3: 'Venom', confluence: 'Chimera' },
	{ essence1: 'Earth', essence2: 'Pangolin', essence3: 'Shark', confluence: 'Chimera' },
	{ essence1: 'Lizard', essence2: 'Spider', essence3: 'Wolf', confluence: 'Chimera' },
	{ essence1: 'Death', essence2: 'Iron', essence3: 'Life', confluence: 'Cyborg' },
	{ essence1: 'Flesh', essence2: 'Iron', essence3: 'Myriad', confluence: 'Cyborg' },
	{ essence1: 'Flesh', essence2: 'Myriad', essence3: 'Technology', confluence: 'Cyborg' },
	{ essence1: 'Flesh', essence2: 'Magic', essence3: 'Water', confluence: 'Cyborg' },
	{ essence1: 'Death', essence2: 'Flesh', essence3: 'Iron', confluence: 'Cyborg' },
	{ essence1: 'Flesh', essence2: 'Iron', essence3: 'Technology', confluence: 'Cyborg' },
	{ essence1: 'Flesh', essence2: 'Might', essence3: 'Technology', confluence: 'Cyborg' },
	{ essence1: 'Balance', essence2: 'Light', essence3: 'Renewal', confluence: 'Cycle' },
	{ essence1: 'Renewal', essence2: 'Sun', essence3: 'Water', confluence: 'Dawn' },
	{ essence1: 'Dark', essence2: 'Light', essence3: 'Sun', confluence: 'Dawn' },
	{ essence1: 'Fire', essence2: 'Omen', essence3: 'Sun', confluence: 'Dawn' },
	{ essence1: 'Hunger', essence2: 'Locust', essence3: 'Plant', confluence: 'Desolate' },
	{ essence1: 'Blood', essence2: 'Hunger', essence3: 'Locust', confluence: 'Desolate' },
	{ essence1: 'Bone', essence2: 'Dust', essence3: 'Sun', confluence: 'Desolate' },
	{ essence1: 'Cold', essence2: 'Hammer', essence3: 'Sickle', confluence: 'Desolate' },
	{ essence1: 'Sand', essence2: 'Sun', essence3: 'Wind', confluence: 'Desolate' },
	{ essence1: 'Earth', essence2: 'Ice', essence3: 'Wind', confluence: 'Desolate' },
	{ essence1: 'Death', essence2: 'Hunger', essence3: 'Plant', confluence: 'Desolate' },
	{ essence1: 'Bow', essence2: 'Corrupt', essence3: 'Song', confluence: 'Discordant' },
	{ essence1: 'Blood', essence2: 'Dark', essence3: 'Sin', confluence: 'Doom' },
	{ essence1: 'Blood', essence2: 'Dark', essence3: 'Omen', confluence: 'Doom' },
	{ essence1: 'Blood', essence2: 'Corrupt', essence3: 'Potent', confluence: 'Doom' },
	{ essence1: 'Death', essence2: 'Potent', essence3: 'Void', confluence: 'Doom' },
	{ essence1: 'Blood', essence2: 'Corrupt', essence3: 'Flesh', confluence: 'Doom' },
	{ essence1: 'Blight', essence2: 'Smoke', essence3: 'Venom', confluence: 'Doom' },
	{ essence1: 'Death', essence2: 'Potent', essence3: 'Vast', confluence: 'Doom' },
	{ essence1: 'Death', essence2: 'Dimension', essence3: 'Zeal', confluence: 'Doom' },
	{ essence1: 'Moon', essence2: 'Omen', essence3: 'Sun', confluence: 'Doom' },
	{ essence1: 'Growth', essence2: 'Hunger', essence3: 'Void', confluence: 'Doom' },
	{ essence1: 'Balance', essence2: 'Omen', essence3: 'Sin', confluence: 'Doom' },
	{ essence1: 'Dark', essence2: 'Hunger', essence3: 'Void', confluence: 'Doom' },
	{ essence1: 'Corrupt', essence2: 'Feast', essence3: 'Growth', confluence: 'Doom' },
	{ essence1: 'Hunger', essence2: 'Magic', essence3: 'Mirror', confluence: 'Doppelganger' },
	{ essence1: 'Flesh', essence2: 'Magic', essence3: 'Mirror', confluence: 'Doppelganger' },
	{ essence1: 'Magic', essence2: 'Might', essence3: 'Wing', confluence: 'Dragon' },
	{ essence1: 'Magic', essence2: 'Potent', essence3: 'Wing', confluence: 'Dragon' },
	{ essence1: 'Balance', essence2: 'Dark', essence3: 'Light', confluence: 'Eclipse' },
	{ essence1: 'Balance', essence2: 'Moon', essence3: 'Sun', confluence: 'Eclipse' },
	{ essence1: 'Balance', essence2: 'Omen', essence3: 'Zeal', confluence: 'Eclipse' },
	{ essence1: 'Balance', essence2: 'Death', essence3: 'Life', confluence: 'Eclipse' },
	{ essence1: 'Dimension', essence2: 'Moon', essence3: 'Sun', confluence: 'Eclipse' },
	{ essence1: 'Earth', essence2: 'Trowel', essence3: 'Vast', confluence: 'Edifice' },
	{ essence1: 'Rune', essence2: 'Star', essence3: 'Tree', confluence: 'Effigy' },
	{ essence1: 'Dance', essence2: 'Glass', essence3: 'Visage', confluence: 'Effigy' },
	{ essence1: 'Blood', essence2: 'Dark', essence3: 'Shimmer', confluence: 'Effigy' },
	{ essence1: 'Magic', essence2: 'Might', essence3: 'Swift', confluence: 'Empower' },
	{ essence1: 'Blood', essence2: 'Growth', essence3: 'Hunger', confluence: 'Empower' },
	{ essence1: 'Might', essence2: 'Renewal', essence3: 'Sin', confluence: 'Empower' },
	{ essence1: 'Elemental', essence2: 'Lightning', essence3: 'Sword', confluence: 'Empower' },
	{ essence1: 'Frog', essence2: 'Hunger', essence3: 'Void', confluence: 'Empower' },
	{ essence1: 'Elemental', essence2: 'Hunger', essence3: 'Potent', confluence: 'Empower' },
	{ essence1: 'Balance', essence2: 'Hunger', essence3: 'Magic', confluence: 'Empower' },
	{ essence1: 'Lightning', essence2: 'Swift', essence3: 'Sword', confluence: 'Empower' },
	{ essence1: 'Balance', essence2: 'Blood', essence3: 'Rune', confluence: 'Empower' },
	{ essence1: 'Cat', essence2: 'Magic', essence3: 'Sun', confluence: 'Empower' },
	{ essence1: 'Crystal', essence2: 'Magic', essence3: 'Sword', confluence: 'Empower' },
	{ essence1: 'Flesh', essence2: 'Growth', essence3: 'Potent', confluence: 'Empower' },
	{ essence1: 'Blood', essence2: 'Hunger', essence3: 'Might', confluence: 'Empower' },
	{ essence1: 'Cat', essence2: 'Fungus', essence3: 'Renewal', confluence: 'Fertile' },
	{ essence1: 'Magic', essence2: 'Pure', essence3: 'Visage', confluence: 'Fey' },
	{ essence1: 'Bird', essence2: 'Fire', essence3: 'Wind', confluence: 'Firebird' },
	{ essence1: 'Magic', essence2: 'Potent', essence3: 'Shield', confluence: 'Force' },
	{ essence1: 'Adept', essence2: 'Magic', essence3: 'Might', confluence: 'Force' },
	{ essence1: 'Balance', essence2: 'Might', essence3: 'Potent', confluence: 'Force' },
	{ essence1: 'Iron', essence2: 'Lightning', essence3: 'Technology', confluence: 'Forge' },
	{ essence1: 'Fire', essence2: 'Iron', essence3: 'Water', confluence: 'Forge' },
	{ essence1: 'Fire', essence2: 'Iron', essence3: 'Technology', confluence: 'Forge' },
	{ essence1: 'Bird', essence2: 'Fire', essence3: 'Iron', confluence: 'Forge' },
	{ essence1: 'Fire', essence2: 'Hammer', essence3: 'Iron', confluence: 'Forge' },
	{ essence1: 'Earth', essence2: 'Iron', essence3: 'Shield', confluence: 'Fortress' },
	{ essence1: 'Bird', essence2: 'Might', essence3: 'Swift', confluence: 'Garuda' },
	{ essence1: 'Might', essence2: 'Swift', essence3: 'Wing', confluence: 'Garuda' },
	{ essence1: 'Dimension', essence2: 'Myriad', essence3: 'Rune', confluence: 'Gate' },
	{ essence1: 'Dimension', essence2: 'Magic', essence3: 'Void', confluence: 'Gate' },
	{ essence1: 'Dimension', essence2: 'Magic', essence3: 'Rune', confluence: 'Gate' },
	{ essence1: 'Fire', essence2: 'Mirror', essence3: 'Venom', confluence: 'Glimeron' },
	{ essence1: 'Earth', essence2: 'Hair', essence3: 'Snake', confluence: 'Gorgon' },
	{ essence1: 'Bird', essence2: 'Cat', essence3: 'Might', confluence: 'Griffin' },
	{ essence1: 'Magic', essence2: 'Shield', essence3: 'Void', confluence: 'Guardian' },
	{ essence1: 'Shield', essence2: 'Trap', essence3: 'Void', confluence: 'Guardian' },
	{ essence1: 'Claw', essence2: 'Malign', essence3: 'Song', confluence: 'Harpy' },
	{ essence1: 'Bird', essence2: 'Discord', essence3: 'Song', confluence: 'Harpy' },
	{ essence1: 'Discord', essence2: 'Song', essence3: 'Wing', confluence: 'Harpy' },
	{ essence1: 'Axe', essence2: 'Hunt', essence3: 'Plant', confluence: 'Harvest' },
	{ essence1: 'Earth', essence2: 'Plant', essence3: 'Sickle', confluence: 'Harvest' },
	{ essence1: 'Myriad', essence2: 'Renewal', essence3: 'Snake', confluence: 'Hydra' },
	{ essence1: 'Life', essence2: 'Magic', essence3: 'Renewal', confluence: 'Immortal' },
	{ essence1: 'Growth', essence2: 'Might', essence3: 'Renewal', confluence: 'Immortal' },
	{ essence1: 'Blood', essence2: 'Potent', essence3: 'Renewal', confluence: 'Immortal' },
	{ essence1: 'Might', essence2: 'Swift', essence3: 'Vehicle', confluence: 'Juggernaut' },
	{ essence1: 'Iron', essence2: 'Might', essence3: 'Swift', confluence: 'Juggernaut' },
	{ essence1: 'Balance', essence2: 'Magic', essence3: 'Rune', confluence: 'Karmic' },
	{ essence1: 'Omen', essence2: 'Rune', essence3: 'Star', confluence: 'Karmic' },
	{ essence1: 'Deep', essence2: 'Myriad', essence3: 'Potent', confluence: 'Kraken' },
	{ essence1: 'Might', essence2: 'Octopus', essence3: 'Vast', confluence: 'Kraken' },
	{ essence1: 'Deep', essence2: 'Might', essence3: 'Octopus', confluence: 'Kraken' },
	{ essence1: 'Fish', essence2: 'Vast', essence3: 'Water', confluence: 'Leviathan' },
	{ essence1: 'Deep', essence2: 'Might', essence3: 'Vast', confluence: 'Leviathan' },
	{ essence1: 'Harmonic', essence2: 'Plant', essence3: 'Water', confluence: 'Lotus' },
	{ essence1: 'Plant', essence2: 'Sword', essence3: 'Water', confluence: 'Lotus' },
	{ essence1: 'Armour', essence2: 'Magic', essence3: 'Technology', confluence: 'Magitech' },
	{ essence1: 'Lightning', essence2: 'Magic', essence3: 'Technology', confluence: 'Magitech' },
	{ essence1: 'Cat', essence2: 'Spike', essence3: 'Venom', confluence: 'Manticore' },
	{ essence1: 'Foot', essence2: 'Knife', essence3: 'Swift', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Gathering', essence3: 'Gun', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Iron', essence3: 'Technology', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Bow', essence3: 'Swift', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Myriad', essence3: 'Sword', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Dance', essence3: 'Sword', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Fire', essence3: 'Hammer', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Needle', essence3: 'Thread', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Foot', essence3: 'Hand', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Dance', essence3: 'Whip', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Gun', essence3: 'Swift', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Gun', essence3: 'Hand', confluence: 'Master' },
	{ essence1: 'Dance', essence2: 'Song', essence3: 'Sword', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Knife', essence3: 'Smoke', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Magic', essence3: 'Sword', confluence: 'Master' },
	{ essence1: 'Cloth', essence2: 'Needle', essence3: 'Thread', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Swift', essence3: 'Sword', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Cloth', essence3: 'Needle', confluence: 'Master' },
	{ essence1: 'Dance', essence2: 'Sword', essence3: 'Thread', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Thread', essence3: 'Whip', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Fire', essence3: 'Iron', confluence: 'Master' },
	{ essence1: 'Adept', essence2: 'Magic', essence3: 'Potent', confluence: 'Master' },
	{ essence1: 'Life', essence2: 'Pure', essence3: 'Renewal', confluence: 'Ministration' },
	{ essence1: 'Cattle', essence2: 'Might', essence3: 'Trap', confluence: 'Minotaur' },
	{ essence1: 'Cattle', essence2: 'Hunt', essence3: 'Might', confluence: 'Minotaur' },
	{ essence1: 'Fire', essence2: 'Light', essence3: 'Water', confluence: 'Mirage' },
	{ essence1: 'Sun', essence2: 'Vast', essence3: 'Water', confluence: 'Mirage' },
	{ essence1: 'Sand', essence2: 'Sun', essence3: 'Visage', confluence: 'Mirage' },
	{ essence1: 'Earth', essence2: 'Growth', essence3: 'Might', confluence: 'Monolith' },
	{ essence1: 'Magic', essence2: 'Might', essence3: 'Staff', confluence: 'Mystic' },
	{ essence1: 'Magic', essence2: 'Omen', essence3: 'Vast', confluence: 'Mystic' },
	{ essence1: 'Magic', essence2: 'Sword', essence3: 'Wind', confluence: 'Mystic' },
	{ essence1: 'Balance', essence2: 'Swift', essence3: 'Wind', confluence: 'Mystic' },
	{ essence1: 'Balance', essence2: 'Dimension', essence3: 'Harmonic', confluence: 'Mystic' },
	{ essence1: 'Iron', essence2: 'Might', essence3: 'Serene', confluence: 'Mystic' },
	{ essence1: 'Dark', essence2: 'Knowledge', essence3: 'Pure', confluence: 'Mystic' },
	{ essence1: 'Dark', essence2: 'Song', essence3: 'Vast', confluence: 'Mystic' },
	{ essence1: 'Adept', essence2: 'Water', essence3: 'Wind', confluence: 'Mystic' },
	{ essence1: 'Balance', essence2: 'Swift', essence3: 'Sword', confluence: 'Mystic' },
	{ essence1: 'Harmonic', essence2: 'Knowledge', essence3: 'Pure', confluence: 'Mystic' },
	{ essence1: 'Balance', essence2: 'Hand', essence3: 'Iron', confluence: 'Mystic' },
	{ essence1: 'Blood', essence2: 'Renewal', essence3: 'Sword', confluence: 'Mystic' },
	{ essence1: 'Cloud', essence2: 'Vast', essence3: 'Void', confluence: 'Nebula' },
	{ essence1: 'Balance', essence2: 'Mirror', essence3: 'Void', confluence: 'Nemesis' },
	{ essence1: 'Earth', essence2: 'Sand', essence3: 'Water', confluence: 'Oasis' },
	{ essence1: 'Vast', essence2: 'Vehicle', essence3: 'Water', confluence: 'Ocean' },
	{ essence1: 'Bow', essence2: 'Gathering', essence3: 'Myriad', confluence: 'Onslaught' },
	{ essence1: 'Might', essence2: 'Swift', essence3: 'Wind', confluence: 'Onslaught' },
	{ essence1: 'Growth', essence2: 'Renewal', essence3: 'Zeal', confluence: 'Onslaught' },
	{ essence1: 'Gun', essence2: 'Might', essence3: 'Vehicle', confluence: 'Onslaught' },
	{ essence1: 'Gun', essence2: 'Vehicle', essence3: 'Wind', confluence: 'Onslaught' },
	{ essence1: 'Might', essence2: 'Potent', essence3: 'Vast', confluence: 'Onslaught' },
	{ essence1: 'Growth', essence2: 'Might', essence3: 'Zeal', confluence: 'Onslaught' },
	{ essence1: 'Adept', essence2: 'Might', essence3: 'Potent', confluence: 'Onslaught' },
	{ essence1: 'Might', essence2: 'Potent', essence3: 'Swift', confluence: 'Onslaught' },
	{ essence1: 'Hand', essence2: 'Might', essence3: 'Swift', confluence: 'Onslaught' },
	{ essence1: 'Adept', essence2: 'Might', essence3: 'Swift', confluence: 'Onslaught' },
	{ essence1: 'Fire', essence2: 'Gun', essence3: 'Vehicle', confluence: 'Onslaught' },
	{ essence1: 'Gun', essence2: 'Might', essence3: 'Potent', confluence: 'Onslaught' },
	{ essence1: 'Myriad', essence2: 'Vast', essence3: 'Visage', confluence: 'Phantasmagoria' },
	{ essence1: 'Fire', essence2: 'Renewal', essence3: 'Wing', confluence: 'Phoenix' },
	{ essence1: 'Bow', essence2: 'Dark', essence3: 'Hunt', confluence: 'Predatory' },
	{ essence1: 'Bow', essence2: 'Hunt', essence3: 'Trap', confluence: 'Predatory' },
	{ essence1: 'Spear', essence2: 'Spider', essence3: 'Wing', confluence: 'Predatory' },
	{ essence1: 'Bow', essence2: 'Spider', essence3: 'Trap', confluence: 'Predatory' },
	{ essence1: 'Chain', essence2: 'Iron', essence3: 'Myriad', confluence: 'Prison' },
	{ essence1: 'Shield', essence2: 'Trap', essence3: 'Vast', confluence: 'Prison' },
	{ essence1: 'Cage', essence2: 'Rune', essence3: 'Trap', confluence: 'Prison' },
	{ essence1: 'Cage', essence2: 'Lightning', essence3: 'Myriad', confluence: 'Prison' },
	{ essence1: 'Gathering', essence2: 'Iron', essence3: 'Might', confluence: 'Prison' },
	{ essence1: 'Feast', essence2: 'Foot', essence3: 'Rabbit', confluence: 'Prosperity' },
	{ essence1: 'Balance', essence2: 'Renewal', essence3: 'Rune', confluence: 'Prosperity' },
	{ essence1: 'Magic', essence2: 'Rune', essence3: 'Vast', confluence: 'Prosperity' },
	{ essence1: 'Growth', essence2: 'Omen', essence3: 'Sun', confluence: 'Prosperity' },
	{ essence1: 'Growth', essence2: 'Renewal', essence3: 'Shield', confluence: 'Prosperity' },
	{ essence1: 'Adept', essence2: 'Balance', essence3: 'Renewal', confluence: 'Prosperity' },
	{ essence1: 'Balance', essence2: 'Echo', essence3: 'Ice', confluence: 'Refracting' },
	{ essence1: 'Bird', essence2: 'Needle', essence3: 'Song', confluence: 'Resonating' },
	{ essence1: 'Crystal', essence2: 'Harmonic', essence3: 'Serene', confluence: 'Resonating' },
	{ essence1: 'Echo', essence2: 'Swift', essence3: 'Wind', confluence: 'Resonating' },
	{ essence1: 'Bird', essence2: 'Might', essence3: 'Vast', confluence: 'Roc' },
	{ essence1: 'Blood', essence2: 'Dimension', essence3: 'Goat', confluence: 'Sacrifice' },
	{ essence1: 'Hunger', essence2: 'Knife', essence3: 'Sun', confluence: 'Sacrifice' },
	{ essence1: 'Dimension', essence2: 'Knife', essence3: 'Sin', confluence: 'Sacrifice' },
	{ essence1: 'Knowledge', essence2: 'Paper', essence3: 'Serene', confluence: 'Scribe' },
	{ essence1: 'Hand', essence2: 'Paper', essence3: 'Rune', confluence: 'Scribe' },
	{ essence1: 'Fire', essence2: 'Iron', essence3: 'Snake', confluence: 'Serpent' },
	{ essence1: 'Fire', essence2: 'Snake', essence3: 'Wind', confluence: 'Serpent' },
	{ essence1: 'Fire', essence2: 'Snake', essence3: 'Water', confluence: 'Serpent' },
	{ essence1: 'Paper', essence2: 'Sword', essence3: 'Visage', confluence: 'Simulacrum' },
	{ essence1: 'Adept', essence2: 'Bow', essence3: 'Hunt', confluence: 'Skirmish' },
	{ essence1: 'Moon', essence2: 'Star', essence3: 'Sun', confluence: 'Sky' },
	{ essence1: 'Star', essence2: 'Sun', essence3: 'Vast', confluence: 'Sky' },
	{ essence1: 'Cloud', essence2: 'Swift', essence3: 'Wind', confluence: 'Sky' },
	{ essence1: 'Swift', essence2: 'Vehicle', essence3: 'Wind', confluence: 'Soaring' },
	{ essence1: 'Bird', essence2: 'Swift', essence3: 'Wind', confluence: 'Soaring' },
	{ essence1: 'Ship', essence2: 'Water', essence3: 'Wind', confluence: 'Soaring' },
	{ essence1: 'Flesh', essence2: 'Magic', essence3: 'Thread', confluence: 'Sovereign' },
	{ essence1: 'Dark', essence2: 'Sin', essence3: 'Water', confluence: 'Sovereign' },
	{ essence1: 'Adept', essence2: 'Potent', essence3: 'Sceptre', confluence: 'Sovereign' },
	{ essence1: 'Adept', essence2: 'Balance', essence3: 'Potent', confluence: 'Sovereign' },
	{ essence1: 'Dark', essence2: 'Star', essence3: 'Sun', confluence: 'Stellar' },
	{ essence1: 'Lightning', essence2: 'Potent', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Deep', essence2: 'Vast', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Fire', essence2: 'Potent', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Lightning', essence2: 'Magic', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Cloud', essence2: 'Crystal', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Dust', essence2: 'Ice', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Hammer', essence2: 'Lightning', essence3: 'Rune', confluence: 'Storm' },
	{ essence1: 'Fire', essence2: 'Gun', essence3: 'Lightning', confluence: 'Storm' },
	{ essence1: 'Sand', essence2: 'Vast', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Earth', essence2: 'Fire', essence3: 'Wind', confluence: 'Storm' },
	{ essence1: 'Flesh', essence2: 'Sin', essence3: 'Visage', confluence: 'Succubus' },
	{ essence1: 'Hunger', essence2: 'Magic', essence3: 'Sin', confluence: 'Succubus' },
	{ essence1: 'Bat', essence2: 'Rabbit', essence3: 'Rat', confluence: 'Swarm' },
	{ essence1: 'Dark', essence2: 'Fire', essence3: 'Rat', confluence: 'Swarm' },
	{ essence1: 'Fire', essence2: 'Venom', essence3: 'Wasp', confluence: 'Swarm' },
	{ essence1: 'Potent', essence2: 'Venom', essence3: 'Wasp', confluence: 'Swarm' },
	{ essence1: 'Duck', essence2: 'Flea', essence3: 'Foot', confluence: 'Swarm' },
	{ essence1: 'Blood', essence2: 'Myriad', essence3: 'Wing', confluence: 'Swarm' },
	{ essence1: 'Magic', essence2: 'Paper', essence3: 'Rune', confluence: 'Talisman' },
	{ essence1: 'Bird', essence2: 'Lightning', essence3: 'Vast', confluence: 'Thunderbird' },
	{ essence1: 'Dimension', essence2: 'Vast', essence3: 'Void', confluence: 'Time' },
	{ essence1: 'Balance', essence2: 'Dimension', essence3: 'Swift', confluence: 'Time' },
	{ essence1: 'Balance', essence2: 'Moon', essence3: 'Water', confluence: 'Tranquil' },
	{ essence1: 'Corrupt', essence2: 'Death', essence3: 'Serene', confluence: 'Tranquil' },
	{ essence1: 'Serene', essence2: 'Tree', essence3: 'Vast', confluence: 'Tranquil' },
	{ essence1: 'Deer', essence2: 'Earth', essence3: 'Hammer', confluence: 'Transfiguration' },
	{ essence1: 'Bear', essence2: 'Growth', essence3: 'Hand', confluence: 'Transfiguration' },
	{ essence1: 'Adept', essence2: 'Elemental', essence3: 'Magic', confluence: 'Transfiguration' },
	{ essence1: 'Balance', essence2: 'Earth', essence3: 'Iron', confluence: 'Transfiguration' },
	{ essence1: 'Flesh', essence2: 'Growth', essence3: 'Water', confluence: 'Transfiguration' },
	{ essence1: 'Bird', essence2: 'Mouse', essence3: 'Whale', confluence: 'Transfiguration' },
	{ essence1: 'Hunt', essence2: 'Moon', essence3: 'Wolf', confluence: 'Transfiguration' },
	{ essence1: 'Blood', essence2: 'Fire', essence3: 'Iron', confluence: 'Transfiguration' },
	{ essence1: 'Axe', essence2: 'Bear', essence3: 'Moon', confluence: 'Transfiguration' },
	{ essence1: 'Hunger', essence2: 'Moon', essence3: 'Wolf', confluence: 'Transfiguration' },
	{ essence1: 'Balance', essence2: 'Fire', essence3: 'Ice', confluence: 'Transfiguration' },
	{ essence1: 'Death', essence2: 'Dimension', essence3: 'Magic', confluence: 'Transgression' },
	{ essence1: 'Blood', essence2: 'Might', essence3: 'Renewal', confluence: 'Troll' },
	{ essence1: 'Moon', essence2: 'Omen', essence3: 'Wind', confluence: 'Twilight' },
	{ essence1: 'Dark', essence2: 'Light', essence3: 'Moon', confluence: 'Twilight' },
	{ essence1: 'Corrupt', essence2: 'Dance', essence3: 'Flesh', confluence: 'Undeath' },
	{ essence1: 'Death', essence2: 'Magic', essence3: 'Sand', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Spider', confluence: 'Undeath' },
	{ essence1: 'Bone', essence2: 'Corrupt', essence3: 'Dance', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Duck', confluence: 'Undeath' },
	{ essence1: 'Death', essence2: 'Flesh', essence3: 'Hunger', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Wolf', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Snake', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Hunger', confluence: 'Undeath' },
	{ essence1: 'Bone', essence2: 'Corrupt', essence3: 'Flesh', confluence: 'Undeath' },
	{ essence1: 'Bat', essence2: 'Blood', essence3: 'Death', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Visage', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Corrupt', essence3: 'Dark', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Bone', essence3: 'Corrupt', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Dark', essence3: 'Death', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Sin', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Moon', confluence: 'Undeath' },
	{ essence1: 'Blood', essence2: 'Death', essence3: 'Hunt', confluence: 'Undeath' },
	{ essence1: 'Mirror', essence2: 'Myriad', essence3: 'Technology', confluence: 'Unity' },
	{ essence1: 'Earth', essence2: 'Plant', essence3: 'Vast', confluence: 'Verdant' },
	{ essence1: 'Earth', essence2: 'Shovel', essence3: 'Water', confluence: 'Verdant' },
	{ essence1: 'Earth', essence2: 'Plant', essence3: 'Rake', confluence: 'Verdant' },
	{ essence1: 'Duck', essence2: 'Iron', essence3: 'Vast', confluence: 'Vessel' },
	{ essence1: 'Balance', essence2: 'Blood', essence3: 'Hunger', confluence: 'Vessel' },
	{ essence1: 'Balance', essence2: 'Life', essence3: 'Needle', confluence: 'Vessel' },
	{ essence1: 'Technology', essence2: 'Vehicle', essence3: 'Wind', confluence: 'Vessel' },
	{ essence1: 'Knowledge', essence2: 'Technology', essence3: 'Vast', confluence: 'Vessel' },
	{ essence1: 'Cloud', essence2: 'Growth', essence3: 'Vehicle', confluence: 'Vessel' },
	{ essence1: 'Iron', essence2: 'Sin', essence3: 'Wind', confluence: 'Vessel' },
	{ essence1: 'Gathering', essence2: 'Magic', essence3: 'Star', confluence: 'Vessel' },
	{ essence1: 'Death', essence2: 'Vehicle', essence3: 'Water', confluence: 'Vessel' },
	{ essence1: 'Rat', essence2: 'Swift', essence3: 'Water', confluence: 'Vessel' },
	{ essence1: 'Dimension', essence2: 'Vast', essence3: 'Vehicle', confluence: 'Vessel' },
	{ essence1: 'Balance', essence2: 'Blood', essence3: 'Crystal', confluence: 'Vessel' },
	{ essence1: 'Duck', essence2: 'Iron', essence3: 'Visage', confluence: 'Vessel' },
	{ essence1: 'Crystal', essence2: 'Magic', essence3: 'Potent', confluence: 'Vessel' },
	{ essence1: 'Dark', essence2: 'Omen', essence3: 'Serene', confluence: 'Vision' },
	{ essence1: 'Eye', essence2: 'Magic', essence3: 'Mirror', confluence: 'Vision' },
	{ essence1: 'Earth', essence2: 'Fire', essence3: 'Potent', confluence: 'Volcano' },
	{ essence1: 'Earth', essence2: 'Fire', essence3: 'Vast', confluence: 'Volcano' },
	{ essence1: 'Shark', essence2: 'Water', essence3: 'Wind', confluence: 'Vortex' },
	{ essence1: 'Trap', essence2: 'Void', essence3: 'Wind', confluence: 'Vortex' },
	{ essence1: 'Deep', essence2: 'Vast', essence3: 'Void', confluence: 'Vortex' },
	{ essence1: 'Corrupt', essence2: 'Dimension', essence3: 'Void', confluence: 'Vortex' },
	{ essence1: 'Dimension', essence2: 'Hunger', essence3: 'Void', confluence: 'Vortex' },
	{ essence1: 'Feast', essence2: 'Magic', essence3: 'Void', confluence: 'Vortex' },
	{ essence1: 'Dark', essence2: 'Void', essence3: 'Wind', confluence: 'Vortex' },
	{ essence1: 'Dance', essence2: 'Needle', essence3: 'Thread', confluence: 'Weave' },
	{ essence1: 'Harmonic', essence2: 'Myriad', essence3: 'Omen', confluence: 'Weave' },
	{ essence1: 'Dance', essence2: 'Myriad', essence3: 'Thread', confluence: 'Weave' },
	{ essence1: 'Flesh', essence2: 'Hunger', essence3: 'Might', confluence: 'Wendigo' },
	{ essence1: 'Balance', essence2: 'Blood', essence3: 'Might', confluence: 'Wrath' },
	{ essence1: 'Might', essence2: 'Potent', essence3: 'Zeal', confluence: 'Wrath' },
	{ essence1: 'Fire', essence2: 'Light', essence3: 'Potent', confluence: 'Wrath' },
	{ essence1: 'Adept', essence2: 'Fire', essence3: 'Zeal', confluence: 'Wrath' },
	{ essence1: 'Fire', essence2: 'Light', essence3: 'Zeal', confluence: 'Wrath' },
	{ essence1: 'Dimension', essence2: 'Light', essence3: 'Potent', confluence: 'Wrath' },
	{ essence1: 'Balance', essence2: 'Might', essence3: 'Zeal', confluence: 'Wrath' },
	{ essence1: 'Balance', essence2: 'Potent', essence3: 'Zeal', confluence: 'Wrath' },
	{ essence1: 'Bird', essence2: 'Vast', essence3: 'Wind', confluence: 'Ziz' }
];
